# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - nightly
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
jobs:
  include:
    - os: osx
      julia: 1.4
      name: "Julia: 1.4"
    # - os: windows
    #   # arch: x64
    #   julia: 1.3
    #   name: "Julia: 1.3"
    # - os: windows
    #   arch: x86
    #   julia: 1.3
    #   name: "Julia: 1.3 (32bit)"
    - stage: Documentation
      julia: 1.0
      script: julia --project=docs -e '
          using Pkg;
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          include("docs/make.jl");'
      after_success: skip
  allow_failures:
    # - arch: x86
    - os: osx # Travis client sometimes fails erroneously on Mac
    - julia: nightly
  fast_finish: true
